#+TITLE: README for Arch Linux Installation-Script
#+AUTHOR: Tim Hilt
#+DATE: 2020-12-07
#+STARTUP: showeverything

* Arch-Linux-Installation-Script

This repository contains a Bash-Script that helps to replicate my current setup.
This document shall describe the preliminaries and post-installation-operations
that shall be executed, in order to replicate my setup.

The script is split into ~install.sh~ and ~post-install.sh~. The script itself
is optimized for being compatible with ~shellcheck~ and optimized for line- and operation-count.

I use KDE as my desktop-environment / window-manager and keep a dwm-installation
around in case i feel the need to invent something.

* Preliminaries

In order to run the script, first the disk has to be partitioned, the
base-groups have to be installed and the ~chroot~-environment has to be entered:

#+BEGIN_SRC shell
cfdisk
mkfs.ext4 /dev/sda1  # Replace with your drive
mount /dev/sda1 /mnt
wifi-menu  # Connect to wifi
pacstrap /mnt base base-devel linux linux-firmware vim
genfstab -Up /mnt > /mnt/etc/fstab
arch-chroot /mnt
#+END_SRC

Before you actually run the script you should check if everything matches your needs.

* Running the script

To run the script enter:

#+BEGIN_SRC shell
pacman -S git
git clone https://github.com/tim-hilt/arch-installation-script
cd arch-installation-script
./install.sh
#+END_SRC

And watch the magic happen. You will be prompted to enter a password every now
and then.

* Post-Installation

After a reboot you can run ~./post-install.sh~.

# TODO: Anything else here?

* Roadmap

- [ ] Clean up mirrorlist
- [ ] Make infomessages colorful
- [ ] dwm with libs (Renders the ~echo~ to ~.xinitrc~ pointless)
- [ ] Dotfiles
- [X] Set up Audio
- [X] Cups for printing
- [X] Set up AUR
- [X] Doom-Emacs together with personal config
- [X] Split into two scripts: Installation and Post-Installation
- [X] Show info-messages
